mongo:
  image: 'mongo:3.0.4'
  ports:
    - "27017:27017"
web:
  build: .
  command: bundle exec rails server -b '0.0.0.0'
  volumes:
    - .:/fda-frd
  ports:
    - "3000:3000"
  links:
    - mongo
